/**  @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    '../Pages/**/*.razor',
    '../Components/**/*.razor',
    '../Shared/**/*.razor',
    '../wwwroot/index.html',
  ],
  safelist: [],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131013',
        surface: '#131013',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-bright': '#393939',
        'surface-variant': '#353534',
        'surface-dim': '#131013',
        primary: '#fff6df',
        'primary-container': '#ffd700',
        'primary-fixed': '#ffe16d',
        'primary-fixed-dim': '#e9c400',
        'on-primary': '#3a3000',
        'on-primary-container': '#705e00',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d0c6ab',
        outline: '#999077',
        'outline-variant': '#4d4732',
        secondary: '#ffb4a8',
        'on-secondary': '#690000',
        'secondary-container': '#920703',
        'on-secondary-container': '#ff9a8a',
        error: '#ffb4ab',
        'on-error': '#690005',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
